plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
    id 'maven-publish'
}

subprojects {
    apply plugin: 'net.fabricmc.fabric-loom'
    apply plugin: 'maven-publish'

    version = project.mod_version + "+" + project.minecraft_version
    group = project.maven_group

    repositories {
        maven { url 'https://maven.nucleoid.xyz' }
        maven { url 'https://maven.supersanta.me/snapshots' }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
        localRuntime "net.fabricmc:fabric-loader:${project.loader_version}"
        compileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
        localRuntime "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    }

    processResources {
        inputs.property "version", project.version

        filesMatching("fabric.mod.json") {
            expand "version": inputs.properties.version
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${project.base.archivesName.get()}"}
        }
    }

    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                artifactId = project.base.archivesName.get()
                from components.java
            }
        }
    }
}
