base.archivesName = "worldreset-api"

repositories {
    maven { url 'https://jitpack.io' }
}

loom {
    runConfigs.clear()
    mods {
        "worldreset-api" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly("net.casualchampionships:arcade-dimensions:${project.arcade_version}")
    localRuntime("net.casualchampionships:arcade-dimensions:${project.arcade_version}")
    compileOnly("io.github.llamalad7:mixinextras-common:0.5.4")
}
